In [187]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

print(f"PyTorch version: {torch.__version__}")

# Check PyTorch has access to MPS (Metal Performance Shader, Apple's GPU architecture)
print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
print(f"Is MPS available? {torch.backends.mps.is_available()}")

# Set the device      
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

PyTorch version: 2.8.0
Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps


### create range of tensors


In [8]:
t1 = torch.arange(start= 0, end=100,step=11)
t1

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

### create tensors like


In [11]:
t2 = torch.zeros_like(input=t1)
t2

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
float_ten = torch.tensor([3.0,6.0],dtype=None)
float_ten.dtype

torch.float32

In [27]:
float_ten2 = torch.tensor([3.0,6.0],dtype=torch.float16)
float_ten2.dtype

torch.float16

In [28]:
float_ten = torch.tensor([3.0,6.0],
                         dtype=None, #data types 32, 16, floatin, comples
                         device=None, #device tensor is on
                         requires_grad=False) #track graidents 
float_ten.dtype

torch.float32

In [29]:
float_ten.device

device(type='cpu')

### pytorch datatype- 3 big errorse
1. not right datatype
2. not right shape
3. not on right device

In [30]:
float16 = float_ten.type(torch.float16)
float16

tensor([3., 6.], dtype=torch.float16)

In [31]:
float16*float_ten

tensor([ 9., 36.])

In [34]:
st = torch.rand(3,4)
print(st)
print(f"datatype: {st.dtype}")
print(f"shape: {st.shape}")
print(f"device: {st.device}")

tensor([[0.1108, 0.5735, 0.4513, 0.7551],
        [0.2965, 0.9682, 0.8663, 0.3517],
        [0.0631, 0.9072, 0.5956, 0.7841]])
datatype: torch.float32
shape: torch.Size([3, 4])
device: cpu


### matrix tensor operations
* add
* subtract
* multipy-element wise
* division
* matrix multiplication

In [36]:
t = torch.tensor([1,2,3])
t+10

tensor([11, 12, 13])

In [37]:
t*10

tensor([10, 20, 30])

In [38]:
t-10

tensor([-9, -8, -7])

In [39]:
torch.mul(t,10)

tensor([10, 20, 30])

In [40]:
torch.add(t, 10)

tensor([11, 12, 13])

In [45]:
#element wise multiplication
t * t

tensor([1, 4, 9])

In [46]:
# matric wise mult
torch.matmul(t, t)

tensor(14)

In [49]:
%%time
val = 0
for i in range(len(t)):
    val+= t[i] * t[i]
print(val)

tensor(14)
CPU times: user 1.96 ms, sys: 1.7 ms, total: 3.66 ms
Wall time: 2.04 ms


In [50]:
%%time
torch.matmul(t, t)

CPU times: user 262 µs, sys: 156 µs, total: 418 µs
Wall time: 343 µs


tensor(14)

### errors - shape errors
1. inner dimensions must match
2. resulting matrix is the outer dimensions

In [51]:
t @ t

tensor(14)

In [53]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## fix by transpose
switches axis


In [57]:
tensor_B, tensor_B.T

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [58]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [59]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [60]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### tensor aggregation - min,max, sum, etc

In [61]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [64]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [65]:
x.dtype

torch.int64

In [66]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [70]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [71]:
x.type(torch.float32).mean()

tensor(45.)

In [74]:
#find position of min in tensor
x.argmin()

tensor(0)

In [75]:
#find position of max in tensor
x.argmax()

tensor(9)

## reshape , stakc, squeeze, unsqueeze
* reshape - reshapes to defined shape
* view - return view of input tensor but same memory (diff pov)
* stack - combine on top of each other
* squeeze - remove 1 dim from tensor
* unsqueeze - add 1 dim to tensor
* permuate - view the input with dimenion permute

In [98]:
x = torch.arange(1.,10.)
x.shape

torch.Size([9])

In [85]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [87]:
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [88]:
x_reshape = x.reshape(3,3)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [91]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [93]:
#chanigng z will change x
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [100]:
#stack tensors on top
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [103]:
x_stack = torch.stack([x,x,x,x], dim=1)
x_stack

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [110]:
x_reshape = x.reshape(1,9)


In [111]:
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


In [113]:
# Remove extra single dimension from x_reshaped
x_squeeze = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeeze}")
print(f"New shape: {x_squeeze.shape}")


New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [118]:
#unsqueeze - add single dimenion
print(f"Previous tensor: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeeze.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [120]:
#permuate - rearnges dim
# Create tensor with specific shape
x_original = torch.rand(size=(225, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([225, 224, 3])
New shape: torch.Size([3, 225, 224])


In [121]:
x_original[0,0,0] = 7238
x_original[0,0,0], x_permuted[0,0,0]

(tensor(7238.), tensor(7238.))

### indexing - similar to pytorch

In [123]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [124]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [127]:
x[0,0]

tensor([1, 2, 3])

In [128]:
x[0][0]

tensor([1, 2, 3])

In [132]:
x[0][2][2]

tensor(9)

In [134]:
x[:, 0]

tensor([[1, 2, 3]])

In [140]:
# all values in the 0th dim, but only the 1,2nd pos
x[:, :, 1]

tensor([[2, 5, 8]])

In [144]:
x[0, 1, 1]

tensor(5)

In [145]:
x[:, 1, 1]

tensor([5])

In [146]:
x[0, 1, :]

tensor([4, 5, 6])

### numpy

numpy -> pytorch = torch.from_numpy(arr)

pytorch -> numpy = torch.Tensor.numpy()

In [156]:
array = np.arange(1.0, 8.0)
array, array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

In [157]:
tensor = torch.from_numpy(array)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), torch.float64)

In [152]:
array = array + 1
array, tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [154]:
t = torch.ones(7)
numpy_t = t.numpy()
t, numpy_t

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [155]:
numpy_t.dtype

dtype('float32')

### reproducability

to reduce randomness in nn and pytorhc - random seed

seed flavor the randomness

In [159]:
torch.rand(3,3)

tensor([[0.2034, 0.6886, 0.8688],
        [0.1060, 0.2160, 0.8545],
        [0.4211, 0.6824, 0.9415]])

In [160]:
rand_a = torch.rand(3,4)
rand_b = torch.rand(3,4)

print(rand_a, rand_b, rand_a==rand_b)

tensor([[0.4771, 0.1581, 0.8329, 0.8036],
        [0.9778, 0.3275, 0.3087, 0.9636],
        [0.3909, 0.7542, 0.7991, 0.4344]]) tensor([[0.1323, 0.8470, 0.9992, 0.1170],
        [0.3844, 0.4618, 0.8424, 0.0558],
        [0.7876, 0.8733, 0.1064, 0.8898]]) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [170]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_d = torch.rand(3,4)

print(rand_c, rand_d, rand_c==rand_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [171]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [172]:
torch.cuda.is_available()

False

In [173]:
print(torch.backends.mps.is_built())

print(torch.backends.mps.is_available())

True
True


In [177]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

print(device)

mps


### tensors on GPU

In [188]:
t = torch.tensor([1,2,3])
print(t, t.device, t.dtype)

tensor([1, 2, 3]) cpu torch.int64


In [189]:
tensor_g = t.to(device)
tensor_g

tensor([1, 2, 3], device='mps:0')

4. tensors back to cpu

In [192]:
tensor_g.cpu().numpy()

array([1, 2, 3])

In [193]:
tensor_g

tensor([1, 2, 3], device='mps:0')